---
driver:
  name: docker
  
provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1
    driver_config:
      image: centos:centos7
      run_command: /usr/sbin/init
      use_sudo: false
      privileged: true

suites:
  - name: default
    run_list:
      - recipe[tomcat::default]
    attributes:
